local M = {}

function M.get(p, groups, styles)
  return {
    Boolean = { fg = p.cyan },
    Character = { fg = p.yellow },
    Comment = { fg = groups.comment, style = styles.italic },
    Conditional = { fg = p.green },
    Constant = { fg = p.yellow },
    Debug = { fg = p.cyan },
    Define = { fg = p.magenta },
    Delimiter = { fg = p.subtle },
    Error = { fg = p.red },
    Exception = { fg = p.green },
    Float = { fg = p.yellow },
    Function = { fg = p.cyan },
    Identifier = { fg = p.cyan },
    -- Ignore = {},
    Include = { fg = p.magenta },
    Keyword = { fg = p.green },
    Label = { fg = p.blue },
    Macro = { fg = p.magenta },
    Number = { fg = p.yellow },
    Operator = { fg = p.subtle },
    PreCondit = { fg = p.magenta },
    PreProc = { fg = p.magenta },
    Repeat = { fg = p.green },
    Special = { fg = p.cyan },
    SpecialChar = { fg = p.cyan },
    SpecialComment = { fg = p.magenta },
    Statement = { fg = p.green },
    StorageClass = { fg = p.blue },
    String = { fg = p.yellow },
    Structure = { fg = p.blue },
    Tag = { fg = p.cyan },
    Todo = { fg = p.magenta },
    Type = { fg = p.blue },
    Typedef = { fg = p.blue },
    Underlined = { style = 'underline' },

    htmlArg = { fg = p.magenta },
    htmlBold = { style = 'bold' },
    htmlEndTag = { fg = p.subtle },
    htmlH1 = { fg = groups.headings.h1, style = 'bold' },
    htmlH2 = { fg = groups.headings.h2, style = 'bold' },
    htmlH3 = { fg = groups.headings.h3, style = 'bold' },
    htmlH4 = { fg = groups.headings.h4, style = 'bold' },
    htmlH5 = { fg = groups.headings.h5, style = 'bold' },
    htmlItalic = { style = styles.italic },
    htmlLink = { fg = groups.link },
    htmlTag = { fg = p.subtle },
    htmlTagN = { fg = p.text },
    htmlTagName = { fg = p.blue },

    markdownDelimiter = { fg = p.subtle },
    markdownH1 = { fg = groups.headings.h1, style = 'bold' },
    markdownH1Delimiter = { link = 'markdownH1' },
    markdownH2 = { fg = groups.headings.h2, style = 'bold' },
    markdownH2Delimiter = { link = 'markdownH2' },
    markdownH3 = { fg = groups.headings.h3, style = 'bold' },
    markdownH3Delimiter = { link = 'markdownH3' },
    markdownH4 = { fg = groups.headings.h4, style = 'bold' },
    markdownH4Delimiter = { link = 'markdownH4' },
    markdownH5 = { fg = groups.headings.h5, style = 'bold' },
    markdownH5Delimiter = { link = 'markdownH5' },
    markdownH6 = { fg = groups.headings.h6, style = 'bold' },
    markdownH6Delimiter = { link = 'markdownH6' },
    markdownLinkText = { fg = groups.link, style = 'underline' },
    markdownUrl = { link = 'markdownLinkText' },

    mkdCode = { fg = p.blue, style = styles.italic },
    mkdCodeDelimiter = { fg = p.cyan },
    mkdCodeEnd = { fg = p.blue },
    mkdCodeStart = { fg = p.blue },
    mkdFootnotes = { fg = p.blue },
    mkdID = { fg = p.blue, style = 'underline' },
    mkdInlineURL = { fg = groups.link, style = 'underline' },
    mkdLink = { link = 'mkdInlineURL' },
    mkdLinkDef = { link = 'mkdInlineURL' },
    mkdListItemLine = { fg = p.text },
    mkdRule = { fg = p.subtle },
    mkdURL = { link = 'mkdInlineURL' },
  }
end

return M
